import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { cn } from "./_utils/tw.utils";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(rubik.className, "overflow-x-hidden")}>
        <div className="w-screen h-screen ">{children}</div>
      </body>
    </html>
  );
}
